---
abstract: 'Pure-Perl Core-Only replacement for pkg-config'
author:
  - 'M. Nunberg <mnunberg@haskalah.org>'
build_requires:
  Archive::Tar: '0'
  Fcntl: '0'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.98, CPAN::Meta::Converter version 2.141170'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: PkgConfig
no_index:
  directory:
    - t
    - inc
requires:
  Test::More: '0'
  perl: '5.006000'
resources:
  repository: https://github.com/mnunberg/perl-PkgConfig.git
version: '0.07620'
