---
abstract: 'Pure-Perl Core-Only replacement for pkg-config'
author:
  - 'M. Nunberg <mnunberg@haskalah.org>'
build_requires:
  Archive::Tar: '0'
  Fcntl: '0'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.98, CPAN::Meta::Converter version 2.141520'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: PkgConfig
no_index:
  directory:
    - t
    - inc
provides:
  PkgConfig:
    file: lib/PkgConfig.pm
    version: 0.08220_01
requires:
  Test::More: '0.94'
  perl: '5.006000'
resources:
  bugtracker: https://github.com/mnunberg/perl-PkgConfig/issues
  homepage: https://metacpan.org/pod/PkgConfig
  repository: https://github.com/mnunberg/perl-PkgConfig.git
version: 0.08220_01
